# dockerfile to build a java-grails image

FROM ubuntu:12.04
MAINTAINER Aman <aman.adsm@gmail.com>

RUN echo 'starting build... creating docker image. Hold On !!'

# OS update & cloning from git
RUN apt-get update && apt-get install -y software-properties-common python-software-properties curl libcurl3 php5-curl git
WORKDIR /home
RUN pwd
RUN git clone https://github.com/Netflix/ice.git &&\ cd ice &&\ ls -al

# Install Java
RUN echo 'Installing java.. .   .'
RUN \
  echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java7-installer
RUN export JAVA_HOME=/usr/lib/jvm/java-7-oracle
RUN java -version

# Install grails
RUN echo 'installing grails.. .   .'
RUN curl -s get.gvmtool.net | bash
RUN gvm help
RUN gvm install grails 2.2.1 -y
RUN grails -version